#! /usr/bin/python
from knockknock import slack_sender
import argparse

SLACK_WEBHOOK_URL = 'https://hooks.slack.com/services/T0JQQQQQQ/B0JQQQQQQ/XXXXXXXXXXXXXXXXXXXXXXXX'
DEFAULT_SLACK_CHANNEL = 'your-slack-channel'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Alert slack')
    parser.add_argument('-c', '--channel', default=DEFAULT_SLACK_CHANNEL, help='Channel')
    parser.add_argument('message', nargs='?', default='OK!', help='Message')
    args = parser.parse_args()

    @slack_sender(webhook_url=SLACK_WEBHOOK_URL, channel=args.channel)
    def alert(message):
        return message
    alert(args.message)